### ISSUE TITLE
Inconsistent behavior between self and others

### ISSUE THREAD

**Issue by athuy** [Pilzinsel64/PlayerTags#6]
When in a duty, the party number / alliance letter indicator is inconsistent between tags applied to self and other players:
Other members seem to have the indicator as considered a part of their name, while the actual user has it considered separate.

See the image below for an example.
![image](https://user-images.githubusercontent.com/91638195/187010334-c7efe484-4be3-44e2-b05f-4fddd7275bef.png)

**Comment by Pilzinsel64** [comment]
Yesterday I investigated about two hours of debugging and testing to the more or less(?) experimental code to see what is going on.
The result: As soon as I get the number with the name at the self linking feature, it doesn't get prepaired at the default chat feature for some reason.

Sadly I had no more time to go deeper. Because I always need someone that get with me together and sit there. Probably I'll do that spontanusly, or someone have more time and make a Pull Request with the fix. :)

**Comment by Pilzinsel64** [comment]
Did some more testings. Fixing the issue on the side of the self linking feature is impossible since you can't create a PlayerPayload that works like you need and for other players.

Fixing in the other direction (moving the number to the left position for all group and alliance members) would be possible somehow but is huge of dirty work.

If someone has the time, feel free to fix that. Also that the last char of a group or allaince member name doesn't count to the player name anymore.

**Comment by Pilzinsel64** [comment]
Fixed in v1.6.7
